import streamlit as st
import tensorflow as tf
from PIL import Image
import numpy as np

st.set_page_config(
    page_title="Plant Disease Detector",
    page_icon="🌱",
    layout="centered"
)
st.markdown("""
<style>
.stApp {
    background: linear-gradient(135deg, #e8f5e9, #c8e6c9, #f1f8e9);
}

h1 {
    color: #1b5e20;
    text-align: center;
    font-size: 45px;
}

h2, h3 {
    color: #2e7d32;
}

p {
    color: #37474f;
    font-size: 17px;
}

.stFileUploader {
    background-color: rgba(255, 255, 255, 0.75);
    border-radius: 15px;
    padding: 10px;
}

.stButton > button {
    width: 100%;
    border-radius: 12px;
    font-size: 18px;
    font-weight: bold;
    padding: 12px;
}
</style>
""", unsafe_allow_html=True)

# Title
st.title("🌱 Plant Disease Detector")

st.write(
    "Upload a plant leaf image and our machine learning model "
    "will predict the plant condition."
)

st.divider()

# Classes
class_names = [
    "Apple Scab Leaf",
    "Apple leaf",
    "Potato leaf early blight",
    "Potato leaf late blight",
    "Tomato Early blight leaf",
    "Tomato leaf",
    "Tomato leaf late blight",
    "grape leaf",
    "grape leaf black rot"
]

# Load model
@st.cache_resource
def load_model():
    return tf.keras.models.load_model("plant_disease_detector.keras")

model = load_model()

# Upload
st.subheader("📤 Upload Leaf Image")

uploaded_file = st.file_uploader(
    "Choose an image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file).convert("RGB")

    st.image(
        image,
        caption="Uploaded Leaf Image",
        use_container_width=True
    )

    st.divider()

    if st.button("🔍 Predict Disease", use_container_width=True):

        # Resize image
        image_resized = image.resize((224, 224))

        # Convert to NumPy array
        image_array = np.array(image_resized)

        # Add batch dimension
        image_array = np.expand_dims(image_array, axis=0)

        # Prediction
        predictions = model.predict(
            image_array,
            verbose=0
        )

        predicted_index = np.argmax(predictions[0])

        predicted_class = class_names[predicted_index]

        confidence = predictions[0][predicted_index] * 100

        # Display result
        st.success(
            f"🌱 Predicted Class: {predicted_class}"
        )

        st.metric(
            "Prediction Confidence",
            f"{confidence:.2f}%"
        )

        st.info(
            "This prediction is generated by the trained "
            "MobileNetV2 machine learning model."
        )

st.divider()

st.caption(
    "Mini Project: Plant Disease Detection using Machine Learning"
)